### ISSUE TITLE
"Merge" feature does not work as expected

### ISSUE THREAD

**Issue by Nakakado** [kroulis/BDOLanguageReplacementTool#3] opened 2024-01-05 18:37 UTC
Hi @kroulis,
First of all thanks for creating this tool.

I am trying to merge the Japanese loc file with English loc file and I am currently experiencing some issues with the **Merge** feature.
The original text and values that are missing from the English localization file are not being displayed correctly as described in the README:
> Functionalities added in 1.1
Added a simple solution to fix missing phrases from a localization file by using the original language file's phrases. Missing phrases will be showing in korean or just blank in game. This solution is shown as the Merge in the Language File Replacement tab.

My expectation is to see Japanese in cases when there is no English translation.
![image](https://github.com/kroulis/BDOLanguageReplacementTool/assets/7533881/8b8f0535-923d-4def-b373-41bed4d55797)
![image](https://github.com/kroulis/BDOLanguageReplacementTool/assets/7533881/de850bb9-64aa-4cac-8d99-108d1165316c)
However all I am seeing are squares for missing data. I have compared both outputs of **Replace** and **Merge** and they both seem the same, so I am suspecting **Merge** is not working as expected.

Is this something you could please look into?

**Comment by kroulis** [comment] 2024-01-05 19:36
Just want to make sure, you did not press replace after merge right?
The replace and merge are different functions, such that if you press replace after merge, the merged localization file will be replaced by the official English version language pack.
Also, I assume you are on the JP server client?

**Comment by Nakakado** [comment] 2024-01-06 18:10
Hi! Your assumption is correct, I am playing on JP server (client).

I have tried multiple use-cases.

1. Replace
2. Replace + Merge
3. Merge + Replace
4. Restore + Replace
5. Restore + Merge + Replace

But I am still seeing squares for missing translations.

Edit: Sorry I closed by mistake.

**Comment by kroulis** [comment] 2024-01-07 01:00
After checking on my end, it seems the language file is merged correctly, I can see that the event related shop items has the original Japanese phrases:
![image](https://github.com/kroulis/BDOLanguageReplacementTool/assets/8529704/8367c305-4bbb-4033-8264-e0f67d145e56)
And from my diffing tool, the merged jp localization file seems aligned with the official JP localization file:
![image](https://github.com/kroulis/BDOLanguageReplacementTool/assets/8529704/07bda6f8-4939-48a9-ba5d-630904c21954)

So at this point, my assumption would be the JP font might not be loaded correctly (i.e. the game might be missing JP font).
Maybe we can try to install the official JP font from the game.
You can use the tool to install the jp font (see the Font Setup tab).
I have uploaded a jp font for testing: [NOTOSANS_REGULAR_JP.ttf](https://github.com/kroulis/BDOLanguageReplacementTool/raw/beta/BDOLangReplacement/Resources/notosans_regular_jp.ttf)

Since I don't have JP BDO account, it could be helpful to do a live debug with discord such that you can share the screen and we can find out what's wrong. If the above does not resolve the issue, please contact me with discord: @kroulis.

**Comment by kroulis** [comment] 2024-02-07 02:33
Issue root cause found.
It seems like certain clients does not load in entries that had duplicated ID except region code.

The merge algorithm needs to be updated.
This will need to be done in 3 steps:

- [x] Update helper tool to add functionalities for removing entries from localizations
- [x] Update the master branch of the tool
- [ ] Update the beta branch of the tool

**Closed as completed** 2024-02-08 04:30 UTC
Labels: bug
